trigger: none
pr: none
pool:
  vmImage: ubuntu-latest
stages:
  - stage: checkParameters
    displayName: Check parameters
    dependsOn: []
    jobs:
      - job: checkParameters
        displayName: Check parameters
        steps:
          - checkout: none

          - script: |-
              set -Eeuxo pipefail
              echo "Subscription name: '$(subscriptionName)'"
              if [ -z "$(subscriptionName)" ]
              then
                echo "A value for the 'subscriptionName' variable must be provided" > /dev/stderr
                exit 1
              fi
              echo "Location name: '$(locationName)'"
              if [ -z "$(locationName)" ]
              then
                echo "A value for the 'locationName' variable must be provided" > /dev/stderr
                exit 1
              fi
              echo "Environment name: '$(environmentName)'"
              if [ -z "$(environmentName)" ]
              then
                echo "A value for the 'environmentName' variable must be provided" > /dev/stderr
                exit 1
              fi
              echo "Subscription ID: '$(subscriptionId)'"
              if [ -z "$(subscriptionId)" ]
              then
                echo "A value for the 'subscriptionId' variable must be provided" > /dev/stderr
                exit 1
              fi
              echo "Application code: '$(applicationCode)'"
              if [ -z "$(applicationCode)" ]
              then
                echo "A value for the 'applicationCode' variable must be provided" > /dev/stderr
                exit 1
              fi
              echo "Application short code: '$(applicationShortCode)'"
              if [ -z "$(applicationShortCode)" ]
              then
                echo "A value for the 'applicationShortCode' variable must be provided" > /dev/stderr
                exit 1
              fi
              echo "Environment category: '$(environmentCategory)'"
              if [ -z "$(environmentCategory)" ]
              then
                echo "A value for the 'environmentCategory' variable must be provided" > /dev/stderr
                exit 1
              fi
      
            displayName: Check parameters

  - stage: deployInfrastructure
    displayName: Deploy infrastructure
    dependsOn:
      - checkParameters
    jobs:
      - template: ../templates/steps-migrate-helm.yaml
        parameters:
          subscriptionName: $(subscriptionName)
          locationName: $(locationName)
          environmentName: $(environmentName)
          subscriptionId: $(subscriptionId)
          applicationCode: $(applicationCode)
          applicationShortCode: $(applicationShortCode)
          environmentCategory: $(environmentCategory)